### ISSUE TITLE
Allow for specifying multiple paths

### ISSUE THREAD

**Issue by jarretlavallee** [puppetlabs/puppet-metrics-viewer#16]
Currently the script only allows a single input path for the metric collection. This is good if you want to import all of the metrics, but you cannot look at a subset of data. 

The script should allow for multiple paths like the following. 

~~~
./view-in-grafana.sh ~/Downloads/pe_metric_curl_cron_jobs/{puppetdb,puppetserver}
~~~

It could also be with additional parameters like the following. 

~~~
./view-in-grafana.sh -p ~/Downloads/pe_metric_curl_cron_jobs/puppetserver -p ~/Downloads/pe_metric_curl_cron_jobs/puppetdb
~~~

This will require a small rewrite of the argument parsing.

**Comment by npwalker** [comment]
I'd suggest taking a base path like we already do but then allow another argument that says which metrics to load (mostly so you don't have to paste the long path twice).  

Could look like `./view-in-grafana.sh ~/Downloads/pe_metric_curl_cron_jobs/ --metric_types "puppetserver, puppetdb"`

**Comment by jarretlavallee** [comment]
Closing as we migrate to https://github.com/puppetlabs/puppet_metrics_dashboard/blob/master/CONTRIBUTING.md#manual-local-testing
