### ISSUE TITLE
Zooming in on PuppetDB data results in the data disappearing 

### ISSUE THREAD

**Issue by npwalker** [puppetlabs/puppet-metrics-viewer#3]
All graphs should set "null value" to connected to ensure that when you zoom in the data does not mystically disappear.  

<img width="1208" alt="null_value_connected" src="https://cloud.githubusercontent.com/assets/513998/25637303/58774ce2-2f39-11e7-8cba-af3c3c62c789.png">

**Comment by jarretlavallee** [comment]
Closing this as #5 is merged.
