### ISSUE TITLE
view-in-grafana.sh should not exit on any key press

### ISSUE THREAD

**Issue by jessereynolds** [puppetlabs/puppet-metrics-viewer#42]
## Use Case

Several times I have accidentally killed the containers by pressing a key while the import process is proceeding, or after it has completed. Most recent case it took 45 mins to import and then immediately exited because I'd hit a key during the import. 

## Describe the Solution You Would Like

When running the `view-in-grafana.sh` script It should ignore any key presses and just print "control-c to exit". 

It would also be great if it printed some info on how stop the containers without losing the imported data, so they can be revived again. 

## Describe Alternatives You've Considered

Alternatively, have the import go into the background and provide `status`, `stop`, `destroy`, `start` type semantics. This would be very nice but more work. 

## Additional Context

Partly the issue is that the same line is printed many times so it's all you see on the screen during import, and once it's scrolled off you've got no idea if it's still going or stalled. It would help if this was turned into a spinner and only each status line that's different from previous were printed to the terminal. 

![Screen Shot 2020-08-19 at 2 28 28 pm](https://user-images.githubusercontent.com/391439/90592187-52909e00-e228-11ea-9949-da878f339610.png)

**Comment by jarretlavallee** [comment]
Closing this as we migrate to the functionality provided by https://github.com/puppetlabs/puppet_metrics_dashboard/blob/master/CONTRIBUTING.md#manual-local-testing

The new method allows for this functionality.
